### PR TITLE
feat: Make color usage and layout normalized

### PR DESCRIPTION
**Pull request by iamareebjamal**
Fixes #[Add issue number here. Note: This will automatically close the issue. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]

Changes: [Add here what changes were made in this issue and if possible provide links.]

Screenshots for the change:

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Fixing a few things and adding screenshots

**Comment by iamareebjamal** [comment]
@shreyasnbhat Please take a look

device-2017-06-07-201002
device-2017-06-07-200326
device-2017-06-07-200306

We needed to use accent color, because in near future, we'll add option to customize the app colors, so they needed to conform to the user need

**Comment by shreyasnbhat** [comment]
@iamareebjamal  Looks neat! 
I think the text such as `EVENT OPEN` etc could be pure white?

**Comment by iamareebjamal** [comment]
OK. Making changes

**Comment by shreyasnbhat** [comment]
@iamareebjamal And we could use the same `SpeakerViewHolder` layout as shown here as this looks much more neat. Harshit says that the existing layout is fine but I strongly disagree.
And if we make the image circle radius similar to the Track Circle Drawable radius would it look better and more uniform?

**Comment by iamareebjamal** [comment]
We can use the layout for speakers which is used in Session Details. But that is work of different PR

**Comment by iamareebjamal** [comment]
About the image radius, sure I agree that will look more uniform

**Comment by shreyasnbhat** [comment]
@iamareebjamal  True I was discussing that with Harshit in the issue of SpeakerFragment UI refresh. But he says that the existing layout is fine and that there is no need to change it.

**Comment by iamareebjamal** [comment]
Well, we'll create mocks and see what everyone thinks

**Comment by shreyasnbhat** [comment]
@iamareebjamal Yeah we could do that.

**Comment by iamareebjamal** [comment]
device-2017-06-07-223249
device-2017-06-07-223219

**Comment by iamareebjamal** [comment]
@shreyasnbhat Please take a look and merge

**Comment by shreyasnbhat** [comment]
@iamareebjamal  Looks good.Merging.

**Pull request merged**
